apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpd-deploy 
  labels:
    app: webserver
    type: html
spec:
  selector:
    matchLabels:
      type: html
  template:
    metadata:
      labels:
        app: webserver
        type: html
    spec:
      containers:
      - image: omprakash1234/webserver
        name: webserver
        ports:
        - containerPort: 80
          name: webserver
  
